### ISSUE TITLE
[Team] 정규 표현식

### ISSUE THREAD

**Issue by dev-Lena** [codesquad-memeber-2020/signup-1#18]
### 아이디
* 최소 5 최대 20자 영 소문자, 숫자, 특수문자(_, -)만 사용 가능
- [x] 완료여부
### 비밀번호
*  8~16자 영문 대/소문자, 숫자, 특수문자 조합
* 영문 대문자 최소 1자이상 포함 
* 숫자 최소 1자이상 포함
* 특수문자 최소 1자 이상 포함
- [x] 완료여부
### 이메일 주소
*  xx@xxx.xxx 형태로 
- [x] 완료여부
### 휴대전화
* 10자리 또는 11자리의 숫자만 입력
* 앞 3자리 숫자는 010만 가능
- [x] 완료여부

📢어떻게 진행할지 의견을 아래 comment로 남겨주세요! 
혹시 FE에 추가적인 부분이 있거나 다른 부분 있으면 업데이트 해주세요~ (@sungik-choi )

**Comment by sungik-choi** [comment]
### 연도

- 4자리의 숫자만

**Comment by ksundong** [comment]
HTML5 의 Email Regex 입니다.
```regex
^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[z-aA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$
```

**Comment by ksundong** [comment]
휴대전화 Regex 간단히 짜봤습니다
```regex
^\d{10,11}$
```

**Comment by ksundong** [comment]
아이디 Regex 입니다. 검증좀 부탁드려요!
```regex
([a-z0-9\-\_]){5,20}
```

**Comment by ksundong** [comment]
비밀번호 Regex입니다. 특수문자 범위를 정해주세요! 현재 !@#$%^&*()_+~` 입력가능합니다.
```regex
^(?=.*[A-Za-z])(?=.*\d)(?=.*[!@#$%^&*()_+~`])[A-Za-z\d!@#$%^&*()_+~`]{8,16}$
```

**Comment by dev-Lena** [comment]
제 생각에는 비밀번호는 ( ,) ,`  특수문자는 없어도 될 것 같아요!

**Comment by ksundong** [comment]
수정해서 반영했습니다.

**Comment by beginin15** [comment]
> 아이디 Regex 입니다. 검증좀 부탁드려요!
> 
> ```regexp
> ([a-z0-9-_]){5,20}
> ```

이거 테스트 해봤는데 20자 넘어가도 match가 뜨는 것 같아용
```
(^[a-z0-9-_]{5,20}$)
```
이렇게 시작과 끝 잡아줘봤는데 제가 잘못이해한걸까용?

**Comment by ksundong** [comment]
@beginin15 수정 후 반영했습니다.
시작 끝을 지정을 안해줬었네요.

불필요한 그룹핑은 제거했습니다~

**Comment by ksundong** [comment]
@codesquad-memeber-2020/signup-1-team-1 

이 Issue Close 해도 될까요?

**Comment by sungik-choi** [comment]
이메일 수정본입니다

```regexp
^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$
```
