### ISSUE TITLE
[FE] 회원가입 양식 UI 구현

### ISSUE THREAD

**Issue by sungik-choi** [codesquad-memeber-2020/signup-1#2]
# 회원가입 양식 UI 구현

- #29  팝업 레이어 별도 이슈 분리
- #27  로그인 화면 별도 이슈 분리

## 개발환경 세팅

- webpack
- babel

## HTML

 > 모바일 네이버 회원가입 참고해보기

- [x] 시맨틱하게 HTML 구조 작성
- Text field(+password), Button
- Label text
- Input text / Placeholder text
- Helper text

## CSS

- [x] SCSS 작성
- SCSS Lint 사용해보기
- Input focus : 테두리색이 변경된다
- Transition

**Comment by dev-Lena** [comment]
FE🐥화이팅!
