### ISSUE TITLE
[Team] 전송하는 field명에 대한 의견

### ISSUE THREAD

**Issue by ksundong** [codesquad-memeber-2020/signup-1#34]
FIELD | DB COLUMN NAME | TYPE
-- | -- | --
🙅‍♂️ | ID(PK) | INT
✅ | USER_ID | VARCHAR
✅ | PASSWORD | VARCHAR
✅ | NAME | VARCHAR
✅ | BIRTH_DAY | DATE
✅ | SEX | ENUM
✅ | EMAIL(Unique) | VARCHAR
✅ | PHONE_NUMBER(Unique) | VARCHAR

INTERESTS | DB COLUMN NAME | TYPE
-- | -- | --
🙅‍♂️ | ID(PK) | INT
✅ | INTEREST | VARCHAR
🙅‍♂️ | UID(FK) | INT

🙅‍♂️ 표시는 따로 네이밍이 필요하지 않습니다.
✅에 대한 네이밍을 추천해주세요.

**Comment by beginin15** [comment]
input에 name에 해당되는 네이밍이죠?

**Comment by ksundong** [comment]
form의 name 들이 해당됩니다.
iOS에서는 어떻게 들어올지 모르겠지만

Json 형식의 key값을 의미한다고 보는게 좋을 것 같아요.

**Comment by beginin15** [comment]
User
+ userId
+ password
+ name
+ birthDay
+ sex
+ email
+ phoneNumber

**Comment by dev-Lena** [comment]
혹시 COLUMN NAME에 대한 의견도 말해도 되나요??
BIRTH_DAY는 한 단어같은데 BIRTHDAY는 어떠신가요??
성은 보통 SEX 보다는 GENDER를 많이 쓰는것 같아요!

저는 카멜 표기법으로 네이밍했으면 좋겠어요!

**Comment by beginin15** [comment]
DB에 column 명도 gender로 바꿀까요?

**Comment by sungik-choi** [comment]
프론트에서 input name, id 를 카멜케이스로 변경하면 되는거죠??

**Comment by sungik-choi** [comment]
위에 제이님이 올려주신 리스트로 변경할까요

**Comment by ksundong** [comment]
@dev-Lena 
좋습니다!! 수정해둘게요!
@sungik-choi 
의견 주시면 적극 수렴하려고 합니다.

**Comment by sungik-choi** [comment]
레나님 말대로 sex -> gender 로 수정하는 부분 좋고, 나머지 네이밍도 동의합니다.
지금 인풋값이 생년월일의 경우 year, month, day 로 되어있는데 이부분을 나중에 모아서 키값을 birthDay로 줘야하는거죠?

**Comment by ksundong** [comment]
@sungik-choi 
네 맞습니다. 그렇게 주시면 spring에서 하나의 객체로 받아줄 수 있어서 좋을 것 같아요!

**Comment by dev-Lena** [comment]
위에 제 의견 반영되면 birthDay가 아니라 birthday 라고 해야할 것 같아요!

**Comment by sungik-choi** [comment]
> 위에 제 의견 반영되면 birthDay가 아니라 birthday 라고 해야할 것 같아요!

저도 이게 좋은거같아요

**Comment by ksundong** [comment]
아 맞아요 이슈작성하다가 다급하게 들어왔는데 벌써 쓰셨네요!

**Comment by ksundong** [comment]
@codesquad-memeber-2020/signup-1-team-1 
더 이상 의견 없으시면 Issue Close 하겠습니다!
