### ISSUE TITLE
[BE] DB의 enum 타입과 객체의 필드 맵핑 문제

### ISSUE THREAD

**Issue by beginin15** [codesquad-memeber-2020/signup-1#43]
- DB에서 지정해준 상수값과 동일한 상수로 맵핑되는 것 같습니다.

- jdbc에서 enum 값을 맵핑하는 방법을 좀 찾아보았는데 해결 방법을 모르겠네요.

- 지금 가능한 방법으로는 DB의 enum 값을 영어로 작성하거나, enum을 String 타입에 저장하거나, 자바 enum의 상수를 한글로 작성해야할 것 같아요!

- 발생한 에러입니다.

>No enum constant com.codesquad.team1.signup.domain.Gender.여자
java.lang.IllegalArgumentException: No enum constant com.codesquad.team1.signup.domain.Gender.여자
	at java.lang.Enum.valueOf(Enum.java:238)

정의된 상수와 동일한 이름으로 바로 찾아가는 것 같아요

**Comment by ksundong** [comment]
@beginin15 
enum('FEMALE', 'MALE')
해당 부분 이렇게 고쳐도 될까요?

**Comment by beginin15** [comment]
@ksundong 넵!

**Comment by ksundong** [comment]
@beginin15 
해당 부분 TB에 우선적용 했습니다. 확인부탁드려요.

**Comment by beginin15** [comment]
@ksundong 해결되었습니다!

**Comment by ksundong** [comment]
```sql
alter table USERS modify GENDER enum('FEMALE', 'MALE') not null;
```
해당 이슈 처리한 쿼리입니다.
