### ISSUE TITLE
[BE] 입력값 유효성 검사 Util

### ISSUE THREAD

**Issue by beginin15** [codesquad-memeber-2020/signup-1#60]
- 회원 가입 시, 입력한 검사가 유효한지 검사하는 Util 클래스를 정의한다.

- 궁금한 점은 유효성 검사를 회원가입 요청 시에 한번에 처리할 지, 혹은 중복 체크처럼 매번 입력할 때마다 실시간으로 검사 결과를 리턴해야할지? 전자가 맞는 것 같은데 어떻게 생각하시나요 @ksundong

**Comment by ksundong** [comment]
Util 클래스 작성하지 않을겁니다.
객체에서 직접 유효성 검증하게 만드는 편이 좋지 않을까요?

회원가입 요청시에 한 번에 처리하는 것으로 생각하고 있습니다.
후자는 앞단에서 하실거에요.

Close 하겠습니다.

**Comment by beginin15** [comment]
@ksundong 패턴 일치하는지 검사하려면 미리 컴파일된 pattern 객체 가지고 하는게 좋을 것 같은데 그런 것들을 Util에 모아서 검사하면 좋지 않을까요? 객체에서 검사하되 Util로 전달해서 검사하도록? 저번에 리뷰하면서 패턴을 미리 만들어놓는게 좋을 것 같다는 얘기를 들어서요~

**Comment by ksundong** [comment]
패턴 객체를 모아놓는 Class만 만들어두면 되는 것 아닐까요?
그걸 Util 클래스에서 들고 있는것도 문제가 되진 않을까요??

**Comment by beginin15** [comment]
@ksundong 그럼 패턴 객체를 모아두는 class를 만드는걸로 할까요? 그럼 객체가 직접 유효성 검사할 때 해당 클래스부터 pattern 객체를 가져와서 검사하는 방식으로?

**Comment by ksundong** [comment]
@beginin15 뭐가 정답이라고 말할 수는 없겠지만, 그 편이 더 좋을 것 같다고 생각합니다!
