### ISSUE TITLE
[Team] 로그인 이후에 이동할 페이지

### ISSUE THREAD

**Issue by beginin15** [codesquad-memeber-2020/signup-1#65]
로그인을 완료한 이후에 어떤 페이지로 이동할지 결정해야될 것 같습니다.

**Comment by sungik-choi** [comment]
메인페이지를 만들어야겠네요. 로그인이랑 메인페이지 만들겠습니다

**Comment by dev-Lena** [comment]
메인 페이지를 만드는 이유가 로그인이 됐는지 확인하는 용도인가요??
혹시 그런거라면 로그인 완료같은 알림창같은걸 띄워도 되지 않을까요?
말씀하시는 메인페이지가 어떤걸까요?? 👀

**Comment by beginin15** [comment]
메인페이지는 계획서에 있던 표현이라서 만들어도 되고 레나가 말한대로 알림창으로 처리해도 되고 뭐로 반응하게 할지 결정하면 될 것 같아요!

**Comment by sungik-choi** [comment]
만들었습니다.

**Comment by dev-Lena** [comment]
아하! 저도 로그인 실패시 알림창 띄우고 성공시 메인 페이지으로 넘어가도록 하겠습니다!

**Comment by ksundong** [comment]
확인했습니다!

**Comment by sungik-choi** [comment]
<img width="685" alt="스크린샷 2020-03-25 오후 3 49 05" src="https://user-images.githubusercontent.com/58209009/77509492-29095b80-6eb0-11ea-824c-8a995b034c4d.png">
<img width="628" alt="스크린샷 2020-03-25 오후 3 51 58" src="https://user-images.githubusercontent.com/58209009/77509705-91583d00-6eb0-11ea-927b-22ad366532c0.png">

고양이는 없애도 돼요.

**Comment by sungik-choi** [comment]
확인하고 이슈 클로즈합니다.
