### ISSUE TITLE
[BE] 중복 체크하는 url을 하나의 메소드로 처리하도록 변경

### ISSUE THREAD

**Issue by beginin15** [codesquad-memeber-2020/signup-1#68]
- /duplicate 으로 요청이 오는 경우, query string으로 어떤 데이터에 대해 중복 검사를 요청하는지 판단하고 처리하도록 변경할 예정입니다.

**Comment by ksundong** [comment]
유연히 대처가 불가능 할 것 같아 Close 합니다.
