### ISSUE TITLE
[BE] 중복 검사 시, 대소문자를 구분하지 않는 버그

### ISSUE THREAD

**Issue by beginin15** [codesquad-memeber-2020/signup-1#72]
- WHERE 절에 BINARY 메소드를 이용하여 대소문자를 구분할 수 있도록 구현할 예정입니다.

**Comment by ksundong** [comment]
좀 더 상세히 이슈내용 적어주시면 감사하겠습니다.

**Comment by beginin15** [comment]
예를 들어서 
현재 DB에 userId가 test가 존재했을 때,
/duplicate?userId=Test 가 요청되는 경우, true가 리턴됩니다.
대소문자를 구분하려면 binary 로 변환해서 체크해주는 것 같아요.

**Comment by ksundong** [comment]
참고문서 같은것도 달아주시면 좋을 것 같습니다.
https://zetawiki.com/wiki/MySQL_대소문자_구별
