### ISSUE TITLE
[BE] FE에서 작성된 화면을 BE의 template에 적용

### ISSUE THREAD

**Issue by ksundong** [codesquad-memeber-2020/signup-1#75]
적용해본적이 없어서 한 번 시도해봐야 합니다.

@sungik-choi 혹시 적용가능한 상태일까요?

https://github.com/codesquad-memeber-2020/signup-1/issues/9
이것과 동시에 진행가능하면 그렇게 하려고 합니다.

**Comment by sungik-choi** [comment]
어.. 일단 지금은 스크립트는 없고 html만 있는 상태입니다

**Comment by ksundong** [comment]
앗 그럼 한 번 집 가서 적용해보겠습니다!

**Comment by ksundong** [comment]
에고 이거 내일 해보겠습니다 ㅠㅠ
