### ISSUE TITLE
[Team] 기능 추가에 대한 라벨 제안드립니다.

### ISSUE THREAD

**Issue by ksundong** [codesquad-memeber-2020/signup-1#84]
다른 그룹은 어떻게 하나 보러갔는데, 

크롱이 이런 리뷰를 남기셨더라고요~
[참고](https://github.com/codesquad-memeber-2020/signup-8/issues/23)

해서 저희도 feature 혹은 task로 label을 분리하는게 어떨까 싶은데, 의견을 주세요!

1. enhancement도 괜찮아요!
2. feature로 가요!
3. task로 가요!
4. 다른 의견이 있어요!

감사합니다.

**Comment by beginin15** [comment]
브랜치명과 동일하게 feature도 좋을 것 같아요! 그럼 리팩토링은 enhancement 라벨을 사용할까요?

**Comment by dev-Lena** [comment]
저는 feature나 task 둘 다 좋아요! Jay 말대로 리팩토링 enhancement 찬성입니다🙌🏻

**Comment by sungik-choi** [comment]
피쳐 좋습니다.!

**Comment by ksundong** [comment]
Feature 라벨 생성하고 이 Issue Close 하겠습니다!

**Comment by ksundong** [comment]
@codesquad-memeber-2020/signup-1-team-1 
Feature 라벨 생성했습니다.
현재 Open되어 있는 Issue 만 Feature 라벨로 각자가 Assign 되어있는 Issue만 변경 부탁드려요!
