### ISSUE TITLE
[BE] 회원 가입 시, 관심사 테이블에도 데이터 추가

### ISSUE THREAD

**Issue by beginin15** [codesquad-memeber-2020/signup-1#88]
- 회원 가입 시, 관심사에 대한 데이터를 테이블에 insert 해야할 것 같습니다.

**Comment by ksundong** [comment]
해당 부분 좀 더 구체화가 가능할 것 같습니다.

- [ ] Interest 객체 생성
- [ ] User 객체에서 Interest를 List로 관리하도록 수정
- [ ] Spring에서 Interest List를 어떻게 처리해주는지 확인

이 세가지 sub task로 나눌 수 있겠네요.
