### ISSUE TITLE
[BE] 세션에 저장되는 로그인 세션 정보 쿠키 Key 값에 대한 논의

### ISSUE THREAD

**Issue by ksundong** [codesquad-memeber-2020/signup-1#90]
SESSION_USER_KEY 라는 상수에 `"sessionedUser"라는 값을 할당할 것인지, 다른 값을 할당할 것인지

선언하는 위치는 어디에 할 건지 논의가 필요하여 이슈 생성합니다.

**Comment by beginin15** [comment]
@ksundong 키값은 네이밍 문제인거죵? 선언하는 위치는 현재로써는 여러 컨트롤러에서 사용하지 않고 있어서 사용되고 있는 클래스에 정의한건데 상수값을 모아놓는 클래스를 만드는 것도 좋을 것 같아요

**Comment by ksundong** [comment]
@beginin15 
이 Issue Close 하고 HttpSessionUtils로 새로운 Issue 생성하시면 될 것 같습니다.

**Comment by beginin15** [comment]
#104 로 새로 생성해서 작업하겠습니다.
